export interface Company {
  id: number;
  address: string;
  name: string;
}

interface Response {
  collection: Company[];
  xTotalCount: number;
}

export default async function fetchCompanies(
  limit: number,
  set: number
): Promise<Response> {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        collection: companies.slice(set, set + limit),
        xTotalCount: companies.length,
      });
    }, 2000);
  });
}

const companies = [
  { id: 1, name: "Компания A", address: "Адрес A" },
  { id: 2, name: "Компания A", address: "Адрес A" },
  { id: 3, name: "Компания A", address: "Адрес A" },
  { id: 4, name: "Компания A", address: "Адрес A" },
  { id: 5, name: "Компания A", address: "Адрес A" },
  { id: 6, name: "Компания A", address: "Адрес A" },
  { id: 7, name: "Компания A", address: "Адрес A" },
  { id: 8, name: "Компания A", address: "Адрес A" },
  { id: 9, name: "Компания A", address: "Адрес A" },
  { id: 10, name: "Компания A", address: "Адрес A" },
  { id: 11, name: "Компания A", address: "Адрес A" },
  { id: 12, name: "Компания A", address: "Адрес A" },
  { id: 13, name: "Компания A", address: "Адрес A" },
  { id: 14, name: "Компания A", address: "Адрес A" },
  { id: 15, name: "Компания A", address: "Адрес A" },
  { id: 16, name: "Компания A", address: "Адрес A" },
  { id: 17, name: "Компания A", address: "Адрес A" },
  { id: 18, name: "Компания A", address: "Адрес A" },
  { id: 19, name: "Компания A", address: "Адрес A" },
  { id: 20, name: "Компания A", address: "Адрес A" },
  { id: 21, name: "Компания A", address: "Адрес A" },
  { id: 22, name: "Компания A", address: "Адрес A" },
  { id: 23, name: "Компания A", address: "Адрес A" },
  { id: 24, name: "Компания A", address: "Адрес A" },
  { id: 25, name: "Компания A", address: "Адрес A" },
  { id: 26, name: "Компания A", address: "Адрес A" },
  { id: 27, name: "Компания A", address: "Адрес A" },
  { id: 28, name: "Компания A", address: "Адрес A" },
  { id: 29, name: "Компания A", address: "Адрес A" },
  { id: 30, name: "Компания A", address: "Адрес A" },
  { id: 31, name: "Компания A", address: "Адрес A" },
  { id: 32, name: "Компания A", address: "Адрес A" },
  { id: 33, name: "Компания A", address: "Адрес A" },
  { id: 34, name: "Компания A", address: "Адрес A" },
  { id: 35, name: "Компания A", address: "Адрес A" },
  { id: 36, name: "Компания A", address: "Адрес A" },
  { id: 37, name: "Компания A", address: "Адрес A" },
  { id: 38, name: "Компания A", address: "Адрес A" },
  { id: 39, name: "Компания A", address: "Адрес A" },
  { id: 40, name: "Компания A", address: "Адрес A" },
  { id: 41, name: "Компания A", address: "Адрес A" },
  { id: 42, name: "Компания A", address: "Адрес A" },
  { id: 43, name: "Компания A", address: "Адрес A" },
  { id: 44, name: "Компания A", address: "Адрес A" },
  { id: 45, name: "Компания A", address: "Адрес A" },
  { id: 46, name: "Компания A", address: "Адрес A" },
  { id: 47, name: "Компания A", address: "Адрес A" },
  { id: 48, name: "Компания A", address: "Адрес A" },
  { id: 49, name: "Компания A", address: "Адрес A" },
  { id: 50, name: "Компания A", address: "Адрес A" },
  { id: 51, name: "Компания A", address: "Адрес A" },
  { id: 52, name: "Компания A", address: "Адрес A" },
  { id: 53, name: "Компания A", address: "Адрес A" },
  { id: 54, name: "Компания A", address: "Адрес A" },
  { id: 55, name: "Компания A", address: "Адрес A" },
  { id: 56, name: "Компания A", address: "Адрес A" },
  { id: 57, name: "Компания A", address: "Адрес A" },
  { id: 58, name: "Компания A", address: "Адрес A" },
  { id: 59, name: "Компания A", address: "Адрес A" },
  { id: 60, name: "Компания A", address: "Адрес A" },
  { id: 61, name: "Компания A", address: "Адрес A" },
  { id: 62, name: "Компания A", address: "Адрес A" },
  { id: 63, name: "Компания A", address: "Адрес A" },
  { id: 64, name: "Компания A", address: "Адрес A" },
  { id: 65, name: "Компания A", address: "Адрес A" },
  { id: 66, name: "Компания A", address: "Адрес A" },
  { id: 67, name: "Компания A", address: "Адрес A" },
  { id: 68, name: "Компания A", address: "Адрес A" },
  { id: 69, name: "Компания A", address: "Адрес A" },
  { id: 70, name: "Компания A", address: "Адрес A" },
  { id: 71, name: "Компания A", address: "Адрес A" },
  { id: 72, name: "Компания A", address: "Адрес A" },
  { id: 73, name: "Компания A", address: "Адрес A" },
  { id: 74, name: "Компания A", address: "Адрес A" },
  { id: 75, name: "Компания A", address: "Адрес A" },
  { id: 76, name: "Компания A", address: "Адрес A" },
  { id: 77, name: "Компания A", address: "Адрес A" },
  { id: 78, name: "Компания A", address: "Адрес A" },
  { id: 79, name: "Компания A", address: "Адрес A" },
  { id: 80, name: "Компания A", address: "Адрес A" },
  { id: 81, name: "Компания A", address: "Адрес A" },
  { id: 82, name: "Компания A", address: "Адрес A" },
  { id: 83, name: "Компания A", address: "Адрес A" },
  { id: 84, name: "Компания A", address: "Адрес A" },
  { id: 85, name: "Компания A", address: "Адрес A" },
  { id: 86, name: "Компания A", address: "Адрес A" },
  { id: 87, name: "Компания A", address: "Адрес A" },
  { id: 88, name: "Компания A", address: "Адрес A" },
  { id: 89, name: "Компания A", address: "Адрес A" },
  { id: 90, name: "Компания A", address: "Адрес A" },
  { id: 91, name: "Компания A", address: "Адрес A" },
  { id: 92, name: "Компания A", address: "Адрес A" },
  { id: 93, name: "Компания A", address: "Адрес A" },
  { id: 94, name: "Компания A", address: "Адрес A" },
  { id: 95, name: "Компания A", address: "Адрес A" },
  { id: 96, name: "Компания A", address: "Адрес A" },
  { id: 97, name: "Компания A", address: "Адрес A" },
  { id: 98, name: "Компания A", address: "Адрес A" },
  { id: 99, name: "Компания A", address: "Адрес A" },
  { id: 100, name: "Компания A", address: "Адрес A" },
  { id: 101, name: "Компания A", address: "Адрес A" },
  { id: 102, name: "Компания A", address: "Адрес A" },
  { id: 103, name: "Компания A", address: "Адрес A" },
  { id: 104, name: "Компания A", address: "Адрес A" },
  { id: 105, name: "Компания A", address: "Адрес A" },
  { id: 106, name: "Компания A", address: "Адрес A" },
  { id: 107, name: "Компания A", address: "Адрес A" },
  { id: 108, name: "Компания A", address: "Адрес A" },
  { id: 109, name: "Компания A", address: "Адрес A" },
  { id: 110, name: "Компания A", address: "Адрес A" },
];
